#ifndef ELECTRICCYLINDER_CYLINDER_COMMAND_H
#define ELECTRICCYLINDER_CYLINDER_COMMAND_H

#define CYLINDER_BROADCAST_ID           0xFFU

#define CYLINDER_CMD_WRITE              0x02U
#define CYLINDER_CMD_SINGLE_CONTROL     0x04U
#define CYLINDER_CMD_FOLLOW_FEEDBACK    0x20U
#define CYLINDER_CMD_POSITION_FEEDBACK  0x21U

#define CYLINDER_CTRL_START             0x04U
#define CYLINDER_CTRL_PAUSE             0x14U
#define CYLINDER_CTRL_CLEAR_FAULT       0x1EU
#define CYLINDER_CTRL_SAVE_PARAMETER    0x20U
#define CYLINDER_CTRL_QUERY_STATUS      0x22U
#define CYLINDER_CTRL_EMERGENCY_STOP    0x23U

#define CYLINDER_TABLE_ID               0x02U
#define CYLINDER_TABLE_BAUD_RATE        0x06U
#define CYLINDER_TABLE_OVERCURRENT      0x08U
#define CYLINDER_TABLE_TARGET_POS       0x0AU
#define CYLINDER_TABLE_MAX_SPEED        0x0EU

#endif /* ELECTRICCYLINDER_CYLINDER_COMMAND_H */
